### ISSUE TITLE
If a forked is renamed the live demo.html link will not work

### ISSUE THREAD

**Issue by ARC-LTER** [EDIorg/ezCatalog#14]
When a forked repository is renamed from ezCatalog the live Demo.html and the iframe link will not have the correct repository name.

To solve this issue I edited build_catalog.yml to include
sed -i 's/ezCatalog/${{github.event.repository.name }}/g' README.md

Jim Laundre

**Comment by ARC-LTER** [comment]
The sed command did not work. Too general it replace ezCatalog in the wrong places.

Perhaps the easy way is to just update the README.md to mention that if the repository is renamed then the links need to be updated.

**Comment by clnsmth** [comment]
Hi Jim (@ARC-LTER). This bug has been hiding in plain sight for a while now. Many thanks for finding it, putting some effort in, and submitting the PR (even if it didn't work out).

I was able to resolve this issue by changing the demo's reference from "servilla" to "EDIorg", so the original GitHub Action sed command could work as intended.

For details see fd892f449941bfb81b1b089cd90a6d846d2e0889.

**Comment by ARC-LTER** [comment]
Hi Colin,  Thanks for changing the demo's reference.  The other issue which I didn't make very clear was that when one forks the repository and give it a name other then ezCatalog the links will not work since it assumes the repository name in the URL is ezCatalog and not what the new name.  
Probably the simple way to deal with this is to mention in the README.md.  Another sed command could change it to the repository's name but it would have to search only the demo.html links.
Jim

**Comment by clnsmth** [comment]
Thanks for your patience @ARC-LTER. What do you think of the proposed fix I just pushed? See: https://github.com/EDIorg/ezCatalog/commit/6eaa74d1874d44c6d12f7c7a8bea383018498476
