### ISSUE TITLE
Error popup when connection to search

### ISSUE THREAD

**Issue by jlaundre** [EDIorg/ezCatalog#17]
I get an Error popup that says "There was an error making the request."  when trying to access the search.  It occurs on my site Arctic LTER and the live demo.

**Comment by clnsmth** [comment]
Thanks for reporting this issue @jlaundre. I will have a look.

**Comment by clnsmth** [comment]
We have increased the rate limiting on the PASTA "cite" service from 3 to 10 requests/sec and burst from 5 to 20. This appears to have resolved the issue for all cases mentioned above.

@jlaundre, when you get a chance, can you please confirm that your ezCatalog is back up and running?

**Comment by jlaundre** [comment]
Hi Colin,

My ezcatalog search page is working now.

Thanks for the quick response

Jim
On Oct 23, 2023 at 2:27 PM -0400, Colin Smith ***@***.***>, wrote:

We have increased the rate limiting on the PASTA "cite" service from 3 to 10 requests/sec and burst from 5 to 20. This appears to have resolved the issue for all cases mentioned above.

@jlaundre<https://github.com/jlaundre>, when you get a chance, can you please confirm that your ezCatalog is back up and running?

**Comment by clnsmth** [comment]
Thanks for confirming @jlaundre, and thanks again for reporting this issue.
