### ISSUE TITLE
The build_catalog workflow creates a new branch 'master' 

### ISSUE THREAD

**Issue by kzollove** [EDIorg/ezCatalog#5]
As it is written, the build_catalog workflow creates a new branch 'master' instead of updating 'main' branch. 

I assume this is not intentional, but if it is, should be mentioned in the instructions.

**Comment by clnsmth** [comment]
Thanks @kzollove, I'll take a look.

**Comment by clnsmth** [comment]
Fixed by e81eff2743482b5b1b13f372ead3f5b3cb79b268
