### ISSUE TITLE
ezCatalog Live Demo continues to show Archbold Field Station data

### ISSUE THREAD

**Issue by kzollove** [EDIorg/ezCatalog#6]
After changing the filter query (Steps 3 and 4) and running build_catalog (Step 5), the Live Demo page still shows data packages from Archbold Field Station and not data packages from the new query.

**Comment by clnsmth** [comment]
Thanks @kzollove for test-driving ezCatalog. Try a hard refresh of the page and let me know if that doesn't work.

**Comment by clnsmth** [comment]
Any update on this issue @kzollove?
